#!/bin/sh

if [ $# -gt 0 ]; then
	cmd=$1
	shift
	exec $(command -v $cmd) $@
fi

set -x


MAP_URI="${MAP_URI:-http://${CONSUL_PORT_8500_TCP_ADDR}:8500/v1/kv/router/ssh/map?raw}"

PREFIX=/var/lib/sshkeysfs

mkdir -p $PREFIX

export

nohup sshkeysfs $PREFIX $MAP_URI -o allow_other &>/dev/null &
sleep 1
if [[ ! -f $PREFIX/passwd ]]; then
	echo "Password-file is missing"
	exit 1
fi

rm /etc/passwd
ln -s $PREFIX/passwd /etc/passwd
ssh-keygen -A
exec /usr/sbin/sshd -D -f /etc/ssh/sshd_config